### ISSUE TITLE
how to convert dll into raw bytes for loader>

### ISSUE THREAD

**Issue by dschaf** [ytmcgamer/FortniteCheatSource#5]

**Comment by ytmcgamer** [comment]
go to gooogle skid 🤡😂😂

**Comment by AustralianDeveloper** [comment]
Get hex code from hex editor, put 0x before each hex byte and a comma after each, paste that into your pasted loader.

**Comment by dschaf** [comment]
hex byte is 2 digits each

**Comment by dschaf** [comment]
@AustralianDeveloper so i open the dll with hxd then?

**Comment by ytmcgamer** [comment]
hxd -> drag pasted cheat dll in -> select everything -> edit -> copy as -> ``C``
